server:
  port: 8080
spring:
  shardingsphere:
    enabled: true
    datasource:
      names: ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
        username: root
        password: lang432105
    sharding:
      default-table-strategy:
        complex:
          sharding-columns: order_id
          algorithm-class-name: cn.lang.algo.TestAlgo
      tables:
        t_order:
          table-strategy:
            complex:
              sharding-columns: order_id
              algorithm-class-name: cn.lang.algo.TestAlgo
          key-generator:
            column: order_id
            type: SNOWFLAKE

